### ISSUE TITLE
Control image is not used in appearance or identity loss guidance

### ISSUE THREAD

**Issue by trwang477** [google-research/readout_guidance#12]
As mentioned in #2, Could you also please address the question of how the control image is used as the ground truth for computing the readout loss? I'm trying to recreate sampling code for identity consistency, how could the conditioning image `edit["control"] = image` control the generation process in current code, as the loss is calculated w.r.t. latent at t not an image? Thank you in advance.

**Comment by g-luo** [comment]
Hi @trwang477, thank you for your question! You might also find #3 and Sec 9.1 of the Supplemental in our [paper](https://arxiv.org/abs/2312.02150) helpful for identity consistency.

- The spatial heads all accept RGB images as the ground truth, and you are correct that the appearance head requires a specific appearance feature for the given image instead. 
- For the appearance head, one thing you can do is given a generated image, cache the intermediate readouts for the appearance feature across all timesteps for the ground truth. We did not experiment with real images in the original paper for identity guidance, but you could also achieve a similar thing via DDIM inversion.

For a more detailed setup of how we do identity guidance for generated images, we do the following:
- We first generate two images with pre-defined seeds (no guidance). We use a face detector to get the `bbox` coordinates for the faces. We then re-generate the images with the same pre-defined seeds, where the first image reconstructs the original identity and the second image is guided with the identity head, constrained to the face regions.
- This solution is not the most elegant, and I would be excited to see if folks had extensions / improvements for what we initially put together!
