### ISSUE TITLE
MayBe A Issue

### ISSUE THREAD

**Issue by OUCHENG-HUANG** [google-research/readout_guidance#8]
rg_pipeline 207 line
When batch_size is 2,there may be issues that exceed the boundaries.

**Comment by g-luo** [comment]
Hi! Are you referencing this [line](https://github.com/google-research/readout_guidance/blob/ba3d7611b9299e25bfba5410a3a4180443772c03/readout_guidance/rg_pipeline.py#L207)?

The codebase should work with the pre-existing demos, all of which have [`batch_size=2`](https://github.com/google-research/readout_guidance/blob/ba3d7611b9299e25bfba5410a3a4180443772c03/configs/drag_generated.yaml#L21). Could you share the code you were running when you were having an issue with the `batch_size`?
